<?php

namespace App\Services;

use App\Models\Options;
use App\Models\Service;
use App\Models\ServiceTier;
use App\Models\Subservice;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class ServiceLifecycleService
{
    public const AUTO_GENERATED_MARKER = '{{-- @auto-generated service blade --}}';

    public function slugFromName(string $name): string
    {
        return Str::slug($name);
    }

    public function normalizeSlug(?string $slug): string
    {
        if ($slug === null || $slug === '') {
            return '';
        }

        return str_replace('_', '-', Str::slug(str_replace('_', '-', $slug)));
    }

    public function bladeComponentSlug(Service $service): string
    {
        return $this->normalizeSlug($service->slug);
    }

    public function bladePathForService(Service $service): string
    {
        return $this->subfolderBladePath($this->bladeComponentSlug($service));
    }

    public function componentViewName(Service $service): string
    {
        $slug = $this->bladeComponentSlug($service);
        $subfolder = 'components.services.'.$slug;
        $flat = 'components.'.$slug;

        if (view()->exists($subfolder)) {
            return $subfolder;
        }

        if (view()->exists($flat)) {
            return $flat;
        }

        return $subfolder;
    }

    public function createBladeIfMissing(Service $service): void
    {
        $slug = $this->bladeComponentSlug($service);
        $subfolderView = 'components.services.'.$slug;
        $flatView = 'components.'.$slug;

        if (view()->exists($subfolderView) || view()->exists($flatView)) {
            return;
        }

        $bladePath = $this->bladePathForService($service);
        File::ensureDirectoryExists(dirname($bladePath));
        File::put($bladePath, $this->buildStarterBladeContent($service->name));
    }

    public function syncBladeOnRename(Service $service, ?string $oldName, ?string $oldSlug): void
    {
        $oldSlugNorm = $this->normalizeSlug($oldSlug ?: $this->slugFromName((string) $oldName));
        $newSlugNorm = $this->bladeComponentSlug($service);

        if ($oldSlugNorm === '' || $oldSlugNorm === $newSlugNorm) {
            $this->createBladeIfMissing($service);

            return;
        }

        $oldPath = $this->findBladeFilePath($oldSlugNorm);
        $newPath = $this->bladePathForService($service);

        if ($oldPath !== null && $this->isAutoGeneratedBlade($oldPath)) {
            if ($oldPath !== $newPath && ! File::exists($newPath)) {
                File::ensureDirectoryExists(dirname($newPath));
                File::move($oldPath, $newPath);
            } elseif ($oldPath !== $newPath && File::exists($newPath)) {
                File::delete($oldPath);
            }
        }

        $this->createBladeIfMissing($service);
    }

    public function deleteBladeForService(Service $service, ?string $oldName = null, ?string $oldSlug = null): void
    {
        $slugs = array_unique(array_filter([
            $this->bladeComponentSlug($service),
            $this->normalizeSlug($oldSlug),
            $oldName ? $this->slugFromName($oldName) : null,
        ]));

        foreach ($slugs as $slug) {
            $path = $this->findBladeFilePath($slug);
            if ($path !== null && $this->isAutoGeneratedBlade($path)) {
                File::delete($path);
            }
        }
    }

    public function deleteRelatedRecords(Service $service): void
    {
        $subservIds = Subservice::query()
            ->where('service_id', $service->service_id)
            ->pluck('subserv_id');

        if ($subservIds->isNotEmpty()) {
            Options::query()->whereIn('subservice_id', $subservIds)->delete();
            Subservice::query()->where('service_id', $service->service_id)->delete();
        }

        ServiceTier::query()->where('service_id', $service->id)->delete();
    }

    public function isAutoGeneratedBlade(string $path): bool
    {
        if (! File::exists($path)) {
            return false;
        }

        return str_contains(File::get($path), self::AUTO_GENERATED_MARKER);
    }

    public function findBladeFilePath(string $slug): ?string
    {
        $slug = $this->normalizeSlug($slug);
        if ($slug === '') {
            return null;
        }

        $subfolderPath = $this->subfolderBladePath($slug);
        if (File::exists($subfolderPath)) {
            return $subfolderPath;
        }

        $flatPath = $this->flatBladePath($slug);
        if (File::exists($flatPath)) {
            return $flatPath;
        }

        return null;
    }

    protected function subfolderBladePath(string $slug): string
    {
        return resource_path('views/components/services/'.$slug.'.blade.php');
    }

    protected function flatBladePath(string $slug): string
    {
        return resource_path('views/components/'.$slug.'.blade.php');
    }

    protected function buildStarterBladeContent(string $serviceName): string
    {
        $title = Str::title($serviceName);
        $marker = self::AUTO_GENERATED_MARKER;

        return <<<BLADE
{$marker}
<div class="container grid sm:grid-flow-row md:grid-cols-1 pb-4">
    <div class="px-4 mt-4">
        <x-titlestyle smheading="Transform Your" bgheading="{$title}!" alignment="text-left" smheadingcolor="" bgheadingcolor=""></x-titlestyle>
        <p class="text-left">{{ \$service }} - We provide comprehensive solutions tailored to your business needs.</p>
        <div class="grid sm:grid-cols-1 md:grid-cols-4 gap-4 my-4">
            @foreach(\$subservices ?? [] as \$subservice)
            @php
            \$slug = str_replace(' ','-', strtolower(\$service));
            \$subslug = str_replace(' ','-', strtolower(\$subservice['subservice_name'] ?? ''));
            \$uniqueId = "subserv_card_" . \$subslug;
            @endphp
            <div class="subserv_card justify-center" id="{{ \$uniqueId }}" data-target="slide_{{\$subslug}}">
                <div class="overflow-hidden shadow-md rounded-lg p-4">
                    <div class="flex justify-center">
                        <div class="h-16 w-16 rounded-md bg-green-500 flex items-center justify-center">
                            @if(isset(\$subservice['icon']))
                            <img class="w-12" src="{{ asset('images/subservices/'.\$subservice['icon']) }}">
                            @endif
                        </div>
                    </div>
                    <div class="flex justify-center">
                        <h2 class="mt-4 text-xl text-center font-bold smalltxt">{{ \$subservice['subservice_name'] ?? 'Subservice' }}</h2>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

<script>
    function highlightRow(checkbox) {
        const row = checkbox.closest('.grid');
        if (checkbox.checked) {
            row.classList.add('highlighted-row');
        } else {
            row.classList.remove('highlighted-row');
        }
    }
</script>
BLADE;
    }
}
