<?php

namespace Tests\Unit;

use App\Models\Service;
use App\Services\ServiceLifecycleService;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

class ServiceLifecycleServiceTest extends TestCase
{
    protected ServiceLifecycleService $lifecycle;

    protected string $servicesBladeDir;

    protected function setUp(): void
    {
        parent::setUp();

        $this->lifecycle = app(ServiceLifecycleService::class);
        $this->servicesBladeDir = resource_path('views/components/services');

        if (! File::isDirectory($this->servicesBladeDir)) {
            File::makeDirectory($this->servicesBladeDir, 0755, true);
        }
    }

    protected function tearDown(): void
    {
        foreach (['test-sync-service', 'renamed-sync-service'] as $slug) {
            $path = $this->servicesBladeDir.DIRECTORY_SEPARATOR.$slug.'.blade.php';
            if (File::exists($path)) {
                File::delete($path);
            }
        }

        parent::tearDown();
    }

    public function test_slug_from_name_uses_hyphenated_slug(): void
    {
        $this->assertSame('software-development', $this->lifecycle->slugFromName('Software Development'));
        $this->assertSame('software-development', Service::slugFromName('Software Development'));
    }

    public function test_create_blade_if_missing_writes_auto_generated_marker(): void
    {
        $service = new Service([
            'name' => 'Test Sync Service',
            'slug' => 'test-sync-service',
        ]);

        $this->lifecycle->createBladeIfMissing($service);

        $path = $this->lifecycle->bladePathForService($service);
        $this->assertFileExists($path);
        $this->assertTrue($this->lifecycle->isAutoGeneratedBlade($path));
        $this->assertStringContainsString(
            ServiceLifecycleService::AUTO_GENERATED_MARKER,
            File::get($path)
        );
    }

    public function test_sync_blade_on_rename_moves_auto_generated_file(): void
    {
        $service = new Service([
            'name' => 'Test Sync Service',
            'slug' => 'test-sync-service',
        ]);

        $this->lifecycle->createBladeIfMissing($service);
        $oldPath = $this->lifecycle->bladePathForService($service);
        $this->assertFileExists($oldPath);

        $service->name = 'Renamed Sync Service';
        $service->slug = 'renamed-sync-service';

        $this->lifecycle->syncBladeOnRename($service, 'Test Sync Service', 'test-sync-service');

        $newPath = $this->lifecycle->bladePathForService($service);
        $this->assertFileExists($newPath);
        $this->assertFileDoesNotExist($oldPath);
    }

    public function test_delete_blade_for_service_removes_only_auto_generated_file(): void
    {
        $service = new Service([
            'name' => 'Test Sync Service',
            'slug' => 'test-sync-service',
        ]);

        $this->lifecycle->createBladeIfMissing($service);
        $path = $this->lifecycle->bladePathForService($service);
        $this->assertFileExists($path);

        $this->lifecycle->deleteBladeForService($service);
        $this->assertFileDoesNotExist($path);
    }

    public function test_delete_blade_for_service_preserves_custom_blade_without_marker(): void
    {
        $customPath = $this->servicesBladeDir.DIRECTORY_SEPARATOR.'custom-hand-edited.blade.php';
        File::put($customPath, '<div>Custom content</div>');

        $service = new Service([
            'name' => 'Custom Hand Edited',
            'slug' => 'custom-hand-edited',
        ]);

        $this->lifecycle->deleteBladeForService($service);
        $this->assertFileExists($customPath);

        File::delete($customPath);
    }
}
